### ISSUE TITLE
Getting std::bad_alloc error when running Object Detector module on Rasberry Pi 3 B+

### ISSUE THREAD

**Issue by Saj1234** [microsoft/azure-iot-edge-cv-model#1]
Hi, I am facing this issue **_std::bad_alloc_** when running the ObjectDetector module on Raspberry Pi 3 B+ and haven't had much luck so far. 

I am using the same onnxruntime-0.5.0-cp35-cp35m-linux_armv7l.whl file to install ONNX runtime  on the container as I was not able to compile a new version from the latest ONNX repo. 
It kept crashing when I tried to do the docker build for ARM 32 from their docker file.

I set up the same ObjectDetector module in my solution and deployed to the edge device.  
ObjectDetector module crashes in predict_yolov3.py when it initializes onnxruntime.

Complete error is below:
`Traceback (most recent call last):
  File "app.py", line 55, in <module>
    model.initialize()
  File "/app/predict_yolov3.py", line 51, in initialize
    session = onnxruntime.InferenceSession(self.model)
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: std::bad_alloc
root@raspberrypi:/home/pi# Loading model...
  File "/app/predict_yolov3.py", line 51, in initialize
    session = onnxruntime.InferenceSession(self.model)
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: std::bad_alloc
`
Not sure if I am doing anything different to this solution. Maybe its something to do with the memory allocation on the edge device. But my other modules on the device work fine.

Can you please point me in the right direction or let me know if there is any update for predict_yolov3.py  file?
Thanks

**Comment by sngdng** [comment]
Hi @Saj1234, how did you proceed to get this error ? what onnx model are you using ? Is it this one [here](https://azurecviotedge.blob.core.windows.net/mlops/model.onnx) ? The error says that it cannot read the model properly !

**Comment by Saj1234** [comment]
Hi @lafius , Yes I used the same model you have specified in this example.  I downloaded the model and placed it in the same location (app folder) of the  module. 
I saw your the recent commit of updating the model link. I also updated the model by downloading it from the same link.
The predict_yolov3.py file is identical to the one in this repo.
```
def initialize(self):
        global session
        print('Loading model...')
        self.get_labels()
        session = onnxruntime.InferenceSession(self.model,)
        print('Model loaded!')
```
this is failing in the initialize method when the onnxruntime load the model.
I thought it was a memory issue due to bad_alloc error.
Just curious why it cant read the model.  I also used the same whl file to install onnxruntime as i could not build one from latest onnxruntime for ARM 32. it keeps failing.

**Comment by sngdng** [comment]
This line session = onnxruntime.InferenceSession(self.model,) should be **session = onnxruntime.InferenceSession(self.model)** without the ,
Well, if you keep having this problem, try to import the ObjectDetection/app/ folder into your Rpi3, install the python dependencies and run app.py directly on your Rpi3, you can debug this way but I tested it and it works well

**Comment by Saj1234** [comment]
@lafius , The comma was a typo when I copy pasted in here. It is same as in the example. However I managed to build and install onnxruntime latest build for ARM32 and it started working.
Thanks
